# Generated by Django 2.0.6 on 2018-06-26 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "01234567890"; 11 digits allowed.', regex='^0\\d{10}$')])),
                ('age_range', models.PositiveSmallIntegerField(choices=[(1, '0-9'), (2, '10-19'), (3, '20-29'), (4, '30-39'), (5, '40-49'), (6, '50-59'), (7, '60-69'), (8, '70-79'), (9, '80-89'), (10, '90-99')], default=4)),
            ],
        ),
    ]
