# Generated by Django 2.0.6 on 2018-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
