# Generated by Django 2.0.6 on 2018-06-27 13:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['photographer', 'number']},
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photos.Photographer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
