# Generated by Django 2.0.6 on 2018-07-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
