# Generated by Django 2.0.6 on 2018-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_field_email_on_photographer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='age_range',
            field=models.PositiveSmallIntegerField(choices=[(0, '0-9'), (1, '10-19'), (2, '20-29'), (3, '30-39'), (4, '40-49'), (5, '50-59'), (6, '60-69'), (7, '70-79'), (8, '80-89'), (9, '90-99')], default=4),
        ),
    ]
