# Generated by Django 2.0.6 on 2018-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_and_photographer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='monument_type',
            field=models.ManyToManyField(blank=True, null=True, to='photos.MonumentType'),
        ),
    ]
