# Generated by Django 2.0.6 on 2018-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_alter_field_monument_type_on_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
