# Generated by Django 2.0.8 on 2018-09-23 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20180923_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='age_range',
            field=models.PositiveSmallIntegerField(choices=[(0, 'undefined'), (1, '0-9'), (2, '10-19'), (3, '20-29'), (4, '30-39'), (5, '40-49'), (6, '50-59'), (7, '60-69'), (8, '70-79'), (9, '80-89'), (10, '90-99')], default=0),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "01234567890"; 11 digits allowed.', regex='^0\\d{10}$')]),
        ),
    ]
