# Generated by Django 2.0.8 on 2018-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20180923_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
