# Generated by Django 2.0.8 on 2018-09-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20180923_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
    ]
