# Generated by Django 2.0.8 on 2018-09-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_photo_subcategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosubcategory',
            options={'ordering': ['category__label', 'label']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='monument_type',
        ),
        migrations.DeleteModel(
            name='MonumentType',
        ),
    ]
