# Generated by Django 2.0.8 on 2018-09-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0018_auto_20180924_0317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photographer',
            unique_together={('email', 'last_name', 'first_name')},
        ),
    ]
