# Generated by Django 2.0.8 on 2018-09-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0019_auto_20180925_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocategory',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='photosubcategory',
            name='label',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='photosubcategory',
            name='slug',
            field=models.SlugField(max_length=60),
        ),
    ]
