# Generated by Django 2.0.8 on 2018-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0022_auto_20180925_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
