# Generated by Django 2.0.8 on 2018-09-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('photos', '0024_auto_20180925_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocategory',
            options={'ordering': ['label'], 'verbose_name_plural': 'Photo Categories'},
        ),
        migrations.AlterModelOptions(
            name='photosubcategory',
            options={'ordering': ['category__label', 'label'], 'verbose_name_plural': 'Photo Subcategories'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='focal_point_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='focal_point_width',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='focal_point_x',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='focal_point_y',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by_user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='width',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
