# Generated by Django 2.0.8 on 2018-09-26 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0025_auto_20180925_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photorendition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='photorendition',
            name='image',
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Photographer'),
        ),
        migrations.DeleteModel(
            name='PhotoRendition',
        ),
    ]
