# Generated by Django 2.0.8 on 2018-10-21 15:00

from django.db import migrations
from ..models import Photo as LatestPhoto


def set_all_photos_public(apps, schema_editor):
    Photo = apps.get_model('photos', 'Photo')
    Photo.objects.all().update(review_status=LatestPhoto.REVIEW_STATUS_PUBLIC)


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0028_auto_20181021_1505'),
    ]

    operations = [
        migrations.RunPython(set_all_photos_public),
    ]
