# Generated by Django 2.0.8 on 2018-10-21 16:27

from django.db import migrations


def convert_photo_date_to_year_month(apps, schema_editor):
    Photo = apps.get_model('photos', 'Photo')
    for photo in Photo.objects.all():
        photo.taken_year = photo.date.year
        photo.taken_month = photo.date.month
        photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0030_auto_20181021_1726'),
    ]

    operations = [
        migrations.RunPython(convert_photo_date_to_year_month),
    ]
