# Generated by Django 2.0.8 on 2018-10-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0031_auto_20181021_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date',
        ),
    ]
