# Generated by Django 2.0.8 on 2018-12-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0035_auto_20181205_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagger_comment', models.TextField()),
                ('reviewer_comment', models.TextField()),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Photo')),
            ],
            options={
                'ordering': ['-updated_at'],
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
            },
        ),
    ]
