# Generated by Django 2.0.9 on 2018-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0038_auto_20181213_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='number',
        ),
        migrations.AlterField(
            model_name='photo',
            name='subcategories',
            field=models.ManyToManyField(to='photos.PhotoSubcategory'),
        ),
    ]
