# Generated by Django 2.0.8 on 2018-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0039_auto_20181214_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographer',
            old_name='gender',
            new_name='gender_category',
        ),
        migrations.AddField(
            model_name='photo',
            name='author_feeling_category',
            field=models.IntegerField(choices=[(-1, 'Positive'), (0, 'Neutral'), (1, 'Negative')], default=0, help_text="Author's feeling about photo"),
        ),
        migrations.AddField(
            model_name='photo',
            name='author_feeling_keywords',
            field=models.TextField(blank=True, default="Author's feelings about photo"),
        ),
        migrations.AddField(
            model_name='photo',
            name='author_focus',
            field=models.TextField(blank=True, default='', help_text="Author's main focus"),
        ),
        migrations.AddField(
            model_name='photo',
            name='author_focus_keywords',
            field=models.CharField(blank=True, default=None, help_text="Author's main focus in three keywords", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='author_reason',
            field=models.TextField(blank=True, default='', help_text='Why did the author take this picture?'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='gender_other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
