# Generated by Django 2.0.8 on 2018-12-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0040_auto_20181219_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author_feeling_category',
            field=models.IntegerField(blank=True, choices=[(-1, 'Positive'), (0, 'Neutral'), (1, 'Negative')], default=None, help_text="Author's feeling about photo", null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author_feeling_keywords',
            field=models.TextField(blank=True, default='', help_text="Keyword describing author's feelings about photo"),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author_reason',
            field=models.TextField(blank=True, default='', help_text='Why did the author take this picture?', verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Internal comments'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='taken_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=None, null=True, verbose_name='Month (photo content)'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='gender_category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unspecified'), (1, 'female'), (2, 'male'), (3, 'other')], default=0),
        ),
    ]
