# Generated by Django 2.1.4 on 2019-01-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0041_auto_20181221_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='photos.PhotoSubcategory'),
        ),
    ]
