# Generated by Django 2.1.4 on 2019-02-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0042_auto_20190102_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author_feeling_category',
            field=models.IntegerField(blank=True, choices=[(-1, 'Positive'), (0, 'Neutral'), (1, 'Negative')], default=None, help_text="Author's feeling about this photo", null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author_feeling_keywords',
            field=models.CharField(blank=True, default='', help_text="Keyword describing author's feelings about this photo", max_length=100),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author_focus_keywords',
            field=models.CharField(blank=True, default=None, help_text="Author's main focus in a few keywords", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author_reason',
            field=models.TextField(blank=True, default='', help_text='Why did the author take this picture?', max_length=500, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='gender_category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'female'), (2, 'male'), (0, 'prefer no to say'), (3, 'other')], default=0),
        ),
    ]
