# Generated by Django 2.1.4 on 2019-02-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0043_auto_20190213_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='legacy_categories',
            field=models.TextField(blank=True, default='', verbose_name='Legacy categories, for reference only'),
        ),
    ]
