# Generated by Django 2.1.4 on 2019-02-13 19:04

from django.db import migrations


def move_photo_cats_to_legacy_cats(apps, schema_editor):
    '''
    See AC-94: we transfer the subcategories into a temp field.
    Editors need to use new categories.
    '''
    Photo = apps.get_model('photos', 'Photo')

    for photo in Photo.objects.all().prefetch_related(
        'subcategories', 'subcategories__category'
    ):
        photo.legacy_categories = ' ; '.join([
            '{}: {}'.format(sub.category.label, sub.label)
            for sub in photo.subcategories.all()
        ])

        photo.subcategories.clear()
        photo.save()

    Category = apps.get_model('photos', 'PhotoCategory')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0044_photo_legacy_categories'),
    ]

    operations = [
        migrations.RunPython(move_photo_cats_to_legacy_cats),
    ]
