# Generated by Django 2.1.4 on 2019-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0045_photo_cats_to_legacy_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='reference_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Reference number'),
        ),
    ]
