# Generated by Django 2.2.1 on 2019-05-20 00:08

from django.db import migrations
import taggit_selectize.managers


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0047_auto_20190519_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=taggit_selectize.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='photos.PhotoTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
